### ISSUE TITLE
great work

### ISSUE THREAD

**Issue by hftsai** [usnistgov/Lineage-Mapper#5]
Dear lineage-mapper development team,
I'm paul and i have been using lineage mapper to analyze my cell migration data and they are working quite well. 

However, I wonder if it's possible to connect lineage mapper with the ROI manager and multimeasure functions, so that not only the centroid (position) data is generated but can use imageJ's measurement function to analyze cell descriptors etc. (having the ROI linking function of the lineage mapper, analyzing the cell descriptors of a cell through out a time lapse)

Thank you

**Comment by mmajurski** [comment]
Paul,
There is currently no method for converting the labeled images into ROIs within the LineageMapper plugin. Especially considering it saves the images to disk directly and does not maintain the entire output labeled image stack in memory. 
However, I do have another plugin which automates Fiji's wand tool to find all objects within a labeled image and create ROIs for them.
https://gist.github.com/mmajurski/39f4eda533c233ed820dab296fb0e27a
If you have experience creating plugins just create an appropriate plugins.config file and compile the jar. If not, send me an email and I will reply with the precompiled jar file from my Fiji plugins folder.
Thanks,
Michael Majurski
michael.majurski@nist.gov
